# --8<-- [start:code]
"""An inverse problem: how much copper has the busbar lost?

The first three tutorials run the model forwards -- geometry in, circuit out. This one runs it
backwards. A busbar has corroded over a known stretch, the only thing that can be measured is its
terminal resistance, and the question is how much metal is gone.

That is the shape every inverse problem has: a **parameter** nobody can see, a **measurement**
everybody can, and a forward model connecting them. What makes it cheap here is that ``jno.peec`` is
differentiable end to end, so the gradient of the measurement with respect to the unknown comes from
the same solve that produced it -- no finite differences, no second model, no adjoint to derive.

The parameter lives in the PROBLEM STATEMENT, exactly as a conductivity always has::

    loss_frac = jno.np.parameter((1,), name="loss_frac")
    bar = jno.Shape.box(...).attach(sigma=CU * (1.0 - loss_frac * corroded))

and because the material now carries a trainable parameter, ``emag.solve().R`` is a **trace node**
rather than a number. So the objective is written the way every other jNO objective is written, and
``jno.core`` threads the values:

    jno.core([((emag.solve().R - R_measured) / R_measured) ** 2]).solve(epochs=250)

The measurement here is SYNTHETIC -- generated by the same model at a known answer -- which is what
makes this a test rather than a demonstration: the recovered number has something to be wrong
against. On real data the truth is exactly what you do not have.
"""

import jax

jax.config.update("jax_enable_x64", True)

import numpy as np  # noqa: E402
import optax  # noqa: E402

import jno  # noqa: E402

CU, mm, P = 5.8e7, 1e-3, 0.8e-3
LOSS_TRUE = 0.65  # the answer we are pretending not to know: 65 % of the copper gone


def busbar(sigma):
    """A 24 mm bar, driven end to end at DC."""
    bar = jno.Shape.box(0, 0, 0, 24 * mm, 4 * mm, P, size=(P,) * 3).attach(sigma=sigma).name("bar")
    d = bar.domain()
    d.tag("A", lambda x, y, z: x < 0.9 * mm)
    d.tag("B", lambda x, y, z: x > 23.1 * mm)
    i, v = d.peec_symbols()
    at = lambda t: d.variable(t, split=True, sample=(2, None))[:3]
    return jno.peec([v(*at("A")) - v(*at("B")) - 1.0], freq=0.0)


# --- which cells are in the corroded stretch: geometry, so it is decided once, on the host --------
lat = busbar(CU).build().fil.lattice
n, lo, d = (np.asarray(lat[k]) for k in ("n", "lo", "d"))
ijk = np.stack(np.meshgrid(*[np.arange(v) for v in n], indexing="ij"), -1).reshape(-1, 3)
x_c = lo[0] + (ijk[:, 0] + 0.5) * d[0]
corroded = ((x_c > 9 * mm) & (x_c < 15 * mm)).astype(float)
print(f"  {corroded.size} cells, {int(corroded.sum())} of them in the corroded stretch")

# --- the measurement, generated at the true answer ------------------------------------------------
R_healthy = float(np.real(busbar(CU).solve().R))
R_measured = float(np.real(busbar(CU * (1.0 - LOSS_TRUE * corroded)).solve().R))
print(f"  healthy  R = {R_healthy * 1e6:.3f} uOhm")
print(f"  measured R = {R_measured * 1e6:.3f} uOhm   ({R_measured / R_healthy:.2f}x)")

# --- the unknown, and the objective -------------------------------------------------------------
# A parameter is born as ZEROS and `.initialize` only records how to fill it, so a starting point is
# not optional here: zero conductivity is a singular network, and `jno.peec` says so by name.
loss_frac = jno.np.parameter((1,), name="loss_frac")
loss_frac.initialize(jax.nn.initializers.constant(0.2))  # a deliberately poor first guess
loss_frac.optimizer(optax.adam(0.03))

emag = busbar(CU * (1.0 - loss_frac * corroded))
residual = ((emag.solve().R - R_measured) / R_measured) ** 2  # R is a TRACE NODE, not a number

crux = jno.core([residual], domain=jno.domain.from_array({"_": np.zeros((1, 1))}))
stats = crux.solve(epochs=250)

recovered = float(np.asarray(crux.eval([loss_frac])).reshape(-1)[0])
history = np.asarray(stats.total_loss_history).reshape(-1)
print(f"\n  objective {history[0]:.3e} -> {history[-1]:.3e}")
print(f"  recovered {recovered:.4f}   truth {LOSS_TRUE}   error {abs(recovered - LOSS_TRUE):.2e}")

assert abs(recovered - LOSS_TRUE) < 1e-3, f"recovered {recovered}, truth {LOSS_TRUE}"
assert history[-1] < 1e-9 * history[0], "the objective must actually be driven down"

# --- the same machinery on a FIELD, which is where it earns its keep -----------------------------
# One unknown from one measurement is a well-posed toy. The interesting case is a density per cell:
# identical code, a parameter of a different shape. Used here as a DESIGN variable -- minimise the
# resistance -- rather than to recover something, which is the other half of what a gradient is for.
#
# The density is BOUNDED BY CONSTRUCTION, `0.5*(1 + tanh(theta))` in (0, 1), and that is not a
# detail: minimising resistance against an unbounded density walks straight past solid copper and
# reports a bar better than the metal it is made of. Bounded, the optimum is known -- fill every
# cell -- so the answer can be checked instead of admired.
theta = jno.np.parameter((int(corroded.size),), name="theta")
theta.initialize(jax.nn.initializers.constant(0.0))  # tanh(0) = 0, so rho starts at 0.5
theta.optimizer(optax.adam(0.2))

rho = 0.5 * (1.0 + jno.np.tanh(theta))
design = jno.core(
    [busbar(CU * rho**3).solve().R * 1e6],
    domain=jno.domain.from_array({"_": np.zeros((1, 1))}),
).solve(epochs=40)

h2 = np.asarray(design.total_loss_history).reshape(-1)
print(f"\n  {corroded.size}-cell density design: R {h2[0]:.3f} -> {h2[-1]:.3f} uOhm")
print(f"  solid copper would be {R_healthy * 1e6:.3f} uOhm -- the optimum it is approaching")
assert h2[-1] < h2[0], "a density field must be able to lower the resistance"
assert h2[-1] > R_healthy * 1e6 - 1e-6, "and must NOT beat solid copper: the density is bounded"
# --8<-- [end:code]
